name: hello_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "3.6.0"
  flutter: "3.27.1"

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: domain
  data:
    path: data
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  go_router: 13.0.0
  flutter_svg: 2.0.0
  fluttertoast: 8.1.2
  flutter_screenutil: 5.9.0
  google_fonts: 6.1.0 # For custom fonts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - env/
    - assets/images/
