name: domain
description: "Domain Layer"
version: 0.0.1
homepage:

environment:
  sdk: "3.6.0"
  flutter: "3.27.1"

dependencies:
  flutter:
    sdk: flutter
  logger: 2.0.2 # For pretty logging
  encrypt: 5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0

flutter:
